###
# Confee API Docker-compose file.
###

# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  confee-mysql-data:
    driver: local

  # Redis Data
  confee-redis-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: confee-mysql
    volumes:
      - confee-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=confee
      - MYSQL_DATABASE=confee
      - MYSQL_USER=confee
      - MYSQL_PASSWORD=confee

  # Redis
  cache:
    image: ambientum/redis:3.2
    container_name: confee-redis
    command: --appendonly yes
    volumes:
      - confee-redis-data:/data
    ports:
      - "6379:6379"

  # Confee API (with Nginx)
  api:
    image: ambientum/php:7.1-nginx
    container_name: confee-api
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
      - cache

  # Laravel Queues
  queue:
    image: ambientum/php:7.1
    container_name: confee-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - cache